name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to run tests for (GITHUB or GITLAB)'
        required: true
        default: 'GITHUB'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.platform }}" == "GITHUB" ]; then
            mvn test -Dsurefire.suiteXmlFiles=testng.xml -Dplatform=GITHUB
          elif [ "${{ github.event.inputs.platform }}" == "GITLAB" ]; then
            mvn test -Dsurefire.suiteXmlFiles=testng.xml -Dplatform=GITLAB
          else
            echo "Invalid platform specified. Please choose either GITHUB or GITLAB."
            exit 1
          fi

      - name: Generate test report
        run: mvn surefire-report:report-only

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/site/surefire-report.html
